# Numerical Gradient Checking

We would highly recommend looking at `neural_networks.grad_check.check_gradients` and making sure you understand how numerical gradient checking is being carried out. This function is used in the notebook to check the gradients of the neural network layers you write. Make sure to check the gradient of a layer after finishing its implementation.

The function returns the relative error of the numerical gradient (approximated using finite differences) with respect to the analytical gradient (computed via backpropagation). Correct implementations should get very small errors, usually less than `1e-8` for 64-bit float matrices (the default).

In [1]:
%load_ext autoreload
%autoreload 2

import numpy as np
from neural_networks.utils import check_gradients
from neural_networks.layers import FullyConnected, Conv2D
from neural_networks.activations import Linear, Sigmoid, TanH, ReLU, SoftMax

## Gradient Checks for Activation Functions

### Linear Activation

In [2]:
X = np.random.randn(2, 3)
dLdY = np.random.randn(2, 3)

# initialize a fully connected layer
# and perform a forward and backward pass
linear_activation = Linear()
_ = linear_activation.forward(X)
grad = linear_activation.backward(X, dLdY)

# check the gradients w.r.t. each parameter
print(
    f"Relative error for linear activation:",
    check_gradients(
        fn=linear_activation.forward,  # the function we are checking
        grad=grad,  # the analytically computed gradient
        x=X,        # the variable w.r.t. which we are taking the gradient
        dLdf=dLdY,  # gradient at previous layer
    )
)

Relative error for linear activation: 3.5997086139496045e-11


### Sigmoid Activation

In [3]:
X = np.random.randn(2, 3)
dLdY = np.random.randn(2, 3)

# initialize a fully connected layer
# and perform a forward and backward pass
sigmoid_activation = Sigmoid()
_ = sigmoid_activation.forward(X)
grad = sigmoid_activation.backward(X, dLdY)

# check the gradients w.r.t. each parameter
print(
    f"Relative error for sigmoid activation:",
    check_gradients(
        fn=sigmoid_activation.forward,  # the function we are checking
        grad=grad,  # the analytically computed gradient
        x=X,        # the variable w.r.t. which we are taking the gradient
        dLdf=dLdY,  # gradient at previous layer
    )
)

AttributeError: 'ellipsis' object has no attribute 'copy'

### Tanh Activation

In [4]:
X = np.random.randn(2, 3)
dLdY = np.random.randn(2, 3)

# initialize a fully connected layer
# and perform a forward and backward pass
tanh_activation = TanH()
_ = tanh_activation.forward(X)
grad = tanh_activation.backward(X, dLdY)

# check the gradients w.r.t. each parameter
print(
    f"Relative error for tanh activation:",
    check_gradients(
        fn=tanh_activation.forward,  # the function we are checking
        grad=grad,  # the analytically computed gradient
        x=X,        # the variable w.r.t. which we are taking the gradient
        dLdf=dLdY,  # gradient at previous layer
    )
)

Relative error for tanh activation: 5.786241988396069e-11


### ReLU Activation

In [5]:
X = np.random.randn(2, 3)
dLdY = np.random.randn(2, 3)

# initialize a fully connected layer
# and perform a forward and backward pass
relu_activation = ReLU()
out = relu_activation.forward(X)
grad = relu_activation.backward(X, dLdY)

# check the gradients w.r.t. each parameter
print(
    f"Relative error for relu activation:",
    check_gradients(
        fn=relu_activation.forward,  # the function we are checking
        grad=grad,  # the analytically computed gradient
        x=X,        # the variable w.r.t. which we are taking the gradient
        dLdf=dLdY,  # gradient at previous layer
    )
)

Relative error for relu activation: 6.768641130783173e-11


### Softmax Activation

In [6]:
X = np.random.randn(2, 3)
dLdY = np.random.randn(2, 3)

# initialize a fully connected layer
# and perform a forward and backward pass
softmax_activation = SoftMax()
_ = softmax_activation.forward(X)
grad = softmax_activation.backward(X, dLdY)

# check the gradients w.r.t. each parameter
print(
    f"Relative error for softmax activation:",
    check_gradients(
        fn=softmax_activation.forward,  # the function we are checking
        grad=grad,  # the analytically computed gradient
        x=X,        # the variable w.r.t. which we are taking the gradient
        dLdf=dLdY,  # gradient at previous layer
    )
)

Relative error for softmax activation: 4.349684939231497e-11


## Gradient Checks for Full Layers (Linear Activations)

### Fully Connected Layer

In [7]:
X = np.random.randn(2, 3)
dLdY = np.random.randn(2, 4)

# initialize a fully connected layer
# and perform a forward and backward pass
fc_layer = FullyConnected(n_out=4, activation="linear")
_ = fc_layer.forward(X)
_ = fc_layer.backward(dLdY)

# check the gradients w.r.t. each parameter
for param in fc_layer.parameters:
    print(
        f"Relative error for {param}:",
        check_gradients(
            fn=fc_layer.forward_with_param(param, X),  # the function we are checking
            grad=fc_layer.gradients[param],  # the analytically computed gradient
            x=fc_layer.parameters[param],  # the variable w.r.t. which we are taking the gradient
            dLdf=dLdY,                     # gradient at previous layer
        )
    )

Relative error for W: 1.321044206229347e-11
Relative error for b: 3.01877174073028e-11


### Conv Layer

In [10]:
X = np.random.randn(2, 5, 6, 7)
dLdY = np.random.randn(2, 5, 6, 4)

# initialize a fully connected layer
# and perform a forward and backward pass
conv_layer = Conv2D(
    n_out=4,
    kernel_shape=(3, 3),
    activation="linear",
    weight_init="uniform",
    pad="same",
)
_ = conv_layer.forward(X)
_ = conv_layer.backward(dLdY)

# check the gradients w.r.t. each parameter
for param in conv_layer.parameters:
    print(
        f"Relative error for {param}:",
        print(param),
        print(conv_layer.gradients[param]),
        print(grad),
        check_gradients(
            fn=conv_layer.forward_with_param(param, X),  # the function we are checking
            grad=conv_layer.gradients[param],  # the analytically computed gradient
            x=conv_layer.parameters[param],  # the variable w.r.t. which we are taking the gradient
            dLdf=dLdY,                     # gradient at previous layer
        )
    )

W
[[[[ 66.62591685  46.24740344 -64.58448283  23.97748331]
   [-17.90429213  13.32476505 -41.33262016 -25.23690246]
   [ 23.25190254  56.15870911  49.45500242  -4.17619592]
   [ -1.40401741 -49.99028345 -35.02568745 -19.36803915]
   [-36.04094659   3.8600905   26.98177987  -9.38675444]
   [-41.4381196   10.25524817  14.95146523  -5.12946873]
   [-49.59775806  10.09956853  31.37343488  -9.99651164]]

  [[-15.68824579 -37.68145382  11.9697868   29.46383342]
   [-60.04072086  -0.67707472 -16.42303504 -12.32614037]
   [-67.50990262  34.79957572 -15.1830228   32.57102912]
   [ 76.44677067 -39.2749448   23.37034711 -13.65308348]
   [ 12.21475163  -2.63124483  52.89033729   0.54957487]
   [ 28.45183759  40.27773483 -56.89804708   7.03766912]
   [ 73.15987924  50.40485273 -51.46643878  14.41585306]]

  [[ -8.41421398   8.25049691  34.85544481   7.97273434]
   [  1.33375463  63.20364079 -62.07806337 -24.25114721]
   [ -9.1496008   26.42549448  -9.92685681  10.29943576]
   [ 26.11215219 -44.5298

In [ ]:
from neural_networks.losses import CrossEntropy

num_pts = 5
num_classes = 6

# one-hot encoded y
y_idxs = np.random.randint(0, num_classes, (num_pts,))
y = np.zeros((num_pts, num_classes))
y[range(num_pts), y_idxs] = 1

# normalized predictions
scores = np.random.uniform(0, 1, size=(num_pts, num_classes))
y_hat = scores / scores.sum(axis=1, keepdims=True)

cross_entropy_loss = CrossEntropy("cross_entropy")

def forward_fn(Y, Y_hat):    
    def inner_forward(Y_hat):
        return cross_entropy_loss.forward(Y, Y_hat)
    return inner_forward

loss = cross_entropy_loss.forward(y, y_hat)
grad = cross_entropy_loss.backward(y, y_hat)

print(
    f"Relative error for cross entropy loss:",
    check_gradients(
        fn=forward_fn(y, y_hat),  # the function we are checking
        grad=grad,  # the analytically computed gradient
        x=y_hat,        # the variable w.r.t. which we are taking the gradient
        dLdf=1,  # gradient at previous layer
    )
)